name: KulichiAPI
version: '2.1'
main: fun.aqurik.KulichiAPI.KulichiAPI
api-version: '1.21'
authors: [Aqurik13, denfry]
description: Kulichi & More
website: https://aqurik.fun
commands:
  getkulichi:
    aliases:
      - getkulich
      - getmorekulich
      - daikulich
    description: Gives kulichi to players
    permission: KulichiAPI.getKulichi
  bankulichi:
    aliases:
      - kban
      - kulichiban
      - block-kulichi
    permission: KulichiAPI.banKulichi
    description: Bans or unbans kulichi
  fban:
    description: Forcefully bans or unbans kulichi
    aliases:
      - forceban
    permission: KulichiAPI.fban
  chlen:
    aliases:
      - penis
      - pipirka
    permission: KulichiAPI.chlen.use
    description: Creates a temporary structure
    usage: "Usage: /chlen"